### ISSUE TITLE
Future development roadmap?

### ISSUE THREAD

**Issue by egardner** [InfiniteLibrary/infinite-electron#13]
# Infinite Library Reader: Next steps

cc: @fchasen @ekmartin @eshellman 

Now that we have a basic version of the app working (hooray!), it would be great to polish things up over the next few weeks/months as time allows. I'm happy to continue doing UI work and implementing other features where I can.

Here are some things I can think we may want to tackle in future development:

- [x] Resize handling (just merged this in to master, but the release has not been updated)
- [ ] Get the "my books" feature working – maybe store a list of the user's "saved" books in LocalStorage?
- [ ] Plug into the unglue.it API for real now that @eshellman has opened it up

Any others?

**Comment by eshellman** [comment]
I'll be working on covers, and on providing a production catalog.

Hadrien got back to me with an updated version of OPDS-JSON which looks a lot nicer than the previous one. I'll be updating the unglue.it feed to align with that. I'll revise rewrite.js to isolate the changes.

For usability and MVP, saving the user's reading position is the only must-have I can think of.

Dan Cohen at DPLA was very impressed.

**Comment by HadrienGardeur** [comment]
Ping me if you need more insights regarding OPDS in JSON.

Just FYI, OPDS and the Readium-2 streamer use exactly the same metadata, so if you're also using the streamer (something that @fchasen hinted at), you could even handle the local shelf that way: one acquisition feed where all the publications are listed and you can directly access each publication's manifest.

**Comment by egardner** [comment]
Are you all familiar with [Standard Ebooks](https://standardebooks.org/)? Looks like a similar effort to expose some of the gems in Project Gutenberg by proofreading, formatting, adding covers, etc. 

It looks like they have an [OPDS feed](https://standardebooks.org/opds/all) – could we add this as a source of data to the app?

**Comment by eshellman** [comment]
I'm working with Alex on https://github.com/Gutenbergbooks
 <https://github.com/Gutenbergbooks>

 <https://github.com/Gutenbergbooks>
Standard Ebooks OPDS is just a static file.

I'll add their feed to Unglue.it

 <https://github.com/Gutenbergbooks>
